services:
  front_react_condominio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: /backend
    container_name: front_react_condominio
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
    networks:
      - infra_net

networks:
  infra_net:
    external: true
    name: infra_net
    driver: bridge